stages:
  - build

build:flutter:
  stage: build
  script:
    - cd flutter
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/public-devosud/docker-images/flutter:latest .
    - docker push $CI_REGISTRY/public-devosud/docker-images/flutter:latest
  tags:
    - docker
    
build:nodeJS:
  stage: build
  script:
    - cd nodeJS
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/public-devosud/docker-images/nodeJS:latest .
    - docker push $CI_REGISTRY/public-devosud/docker-images/nodeJS:latest
  tags:
    - docker
    
build:docken:
  stage: build
  script:
    - cd docken
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/public-devosud/docker-images/docken:latest .
    - docker push $CI_REGISTRY/public-devosud/docker-images/docken:latest
  tags:
    - docker
