stages:
  - build

build:flutter:
  stage: build
  script:
    - cd flutter
    - docker build -t flutter-image .
  tags:
    - docker
    
build:gradle:
  stage: build
  script:
    - cd gradle
    - docker build -t gradle-image .
  tags:
    - docker
    
build:maven:
  stage: build
  script:
    - cd maven
    - docker build -t maven-image .
  tags:
    - docker
