stages:
  - build

build:flutter:
  stage: build
  script:
    - cd flutter
    - docker build -t flutter-image .
  tags:
    - docker
    
build:spring:
  stage: build
  script:
    - cd spring
    - docker build -t spring-image .
  tags:
    - docker
    